version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'

  redis:
    image: redis
    ports:
      - '6379:6379'

  receiver:
    build: ./receiver
    ports:
      - '3000:3000'
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - REDIS_URI=redis://redis:6379
      - PORT=3000
    depends_on:
      - mongo
      - redis

  listener:
    build: ./listener
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - REDIS_URI=redis://redis:6379
      - PORT=3001
    depends_on:
      - mongo
      - redis
